user_view/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from django.views.generic import RedirectView

urlpatterns = [

    url(r'^login/$', auth_views.login, name='login'),
    url(r'^$', auth_views.login, name='login'),
    url(r'logout/', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^user/$', views.index, name='user'),
    url(r'^admin/$', views.admin, name='admin'),
    url(r'^wniosek/$', views.wniosek, name='wniosek'),
    url(r'^thanks/$', views.thanks, name='thanks'),
    url(r'^month_reach_bonus/4324ffsfs42$', views.send_update_request),
    url(r'^(?P<hash>[a-z0-9]+)/(?P<user_id>[0-9]+)/(?P<days>[0-9]+)/(?P<days_bonus>((\d+-\d+-\d+),?\+?)+)/$', views.update_bonus, name='update'),
    url(r'^(?P<hash>[a-z0-9]+)/update_all/(?P<status>[0-1])$', views.update_all, name='update_all'),
    url(r'^modkal/$', views.pickuser, name='pickuser'),
    url(r'^modkal/(?P<client_id>[0-9]+)/(?P<admin_id>[0-9]+)/$', views.modifycalendar, name='modifycalendar'),
    url(r'^resetpasswordconfirm/(?P<uidb64>[0-9A-Za-z]+)/$', views.reset_password_confirm, name='reset_password_confirm'),
    url(r'^reset_password', views.reset_password, name='reset_password'),
    url(r'^createuser/$', views.create_user, name='create_user'),
    url(r'^resetdays/czego1szukasz2ancymonie3barbarzynco4$', views.reset_days, name='reset_days'),
    url(r'^backup/$', views.backup, name='backup'),
    url(r'^sprawdz/$', views.checkcallendar, name='checkcallendar'),
    url(r'^forceb/(?P<user_id>[0-9]+)/(?P<days>[0-9]+)/$', views.force_bonus, name='force')

]

user_view/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User


MONTHS_TUPLE = (
    (1, "Styczeń"),
    (2, "Luty"),
    (3, "Marzec"),
    (4, "Kwiecień"),
    (5, "Maj"),
    (6, "Czerwiec"),
    (7, "Lipiec"),
    (8, "Sierpień"),
    (9, "Wrzesień"),
    (10, "Październik"),
    (11, "Listopad"),
    (12, "Grudzień")
)
YEAR_TUPLE = {
    (2020, "2020"),
    (2019, "2019"),
    (2018, "2018"),
    (2017, "2017")
}


class ContactForm(forms.Form):
    days_quant = forms.IntegerField(label=u'Ilość dni')
    days_bonus = forms.CharField(widget=forms.Textarea, label=u'Dni wzięte')


class ReportForm(forms.Form):
    month = forms.ChoiceField(
        required=True,
        label=u'Miesiąc do raportu',
        choices=MONTHS_TUPLE
    )
    year = forms.ChoiceField(
        required=True,
        label=u'Rok do raportu',
        choices=YEAR_TUPLE
    )

class PickUserForm(forms.Form):
    client = forms.ModelChoiceField(
        queryset=User.objects.all(),
        empty_label=None,
        label='Użytkownik'
    )


class ModifyUserForm(forms.Form):
    user = forms.IntegerField(label=u'User ID')
    username = forms.CharField(label=u'Imię')
    surname = forms.CharField(label=u'Nazwisko')
    days_quant = forms.IntegerField(label=u'Ilość dni')
    days_bonus = forms.CharField(widget=forms.Textarea, label=u'Dni wzięte')


class PasswordResetRequestForm(forms.Form):
    email = forms.CharField(label="Adres E-mail", max_length=254)


class PasswordResetConfirmationForm(forms.Form):
    email = forms.CharField(label="Adres E-mail", max_length=254)
    new_passsword = forms.CharField(label="Nowe hasło", max_length=254, widget=forms.PasswordInput())
    new_passsword_re = forms.CharField(label="Powrórz nowe hasło", max_length=254, widget=forms.PasswordInput())


class NewUserForm(forms.Form):
    username = forms.CharField(label="Nazwa")
    email = forms.CharField(label="Email")
    first_name = forms.CharField(label="Imię")
    last_name = forms.CharField(label="Nazwisko")
    manager_email = forms.CharField(label="Email managera")

user_view/templates/user_view/add-user.html
{% extends 'user_view/base.html' %}
{% block head %}
<link rel="stylesheet" href="./../../static/add-user.css">
{% endblock head %}
{% block content %}
{% if user.is_authenticated %}
{% if request.user.is_superuser %}
<p>Aby stworzyć nowego użytkownika wypełnij poniższy formularz.</p>
<form method="POST">
    {% csrf_token %}
    {{form}}

    <div class="form-actions">
        <button type="submit" class="submit">Dodaj użytkownika</button>
    </div>
</form>
{% endif %}
{% endif %}
{% endblock content%}

user_view/templates/user_view/admin-potwierdzenie.html
<html>
<body>
<h3>Potwierdzenie</h3>

<p>Proszę potwierdzić BONUS Wakacje o wartości {{ days }} dni dla użytkownika {{ client_name }} {{ client_surname }}. </p>
<p>Wartość BONUSA obejmuje dni: <span style="display:none;" id="sp">{{ days_bonus }}</span></p>
<p><a href="{{ url | escape }}">Kliknij w link aby zaakceptować.</a>

</p>
<script>
    var s = document.getElementById('sp'),
    ss=s.innerText;
    ss = ss.replace(/"/g,'').replace(/\[/g,'').replace(/\]/g,'')
    s.innerText=ss;
    document.getElementById('sp').style.display="initial";
</script>
</body>
</html>

user_view/templates/user_view/admin.html
{% extends 'user_view/base.html' %}

{% block head %}
<link rel="stylesheet" href="./../../static/admin.css">
{% endblock head %}
{% block content %}
{% if user.is_authenticated %}
    {% if request.user.is_superuser %}
    <div class="row">   
    <table class="table table-striped" style="width:70%;">
        <tr><td>id</td><td>username</td><td>bonus</td><td></td><td>dni wzięte</td><td>manager</td><td>oczekujące</td></tr>
        {% for user in all_users %}
        <tr>
            <td>{{user.id}}</td>
            <td>{{ user.username }}</td>
             <td>
                 <input type=number name="u{{user.id}}" value="{{ user.bonus.bonus}}" min="1" max="25" maxlength="4" size="5" step="0.1" onkeydown="return false"/>
                    </td>
        <td><button class="btn change" id="u{{user.id}}">Zmień</button></td>
            <td class="bonusdays">{{ user.bonusdays.date_bonus}}</td>
            <td>{{user.manager.email}}</td>
            <td>
                {% if user.pending.status == 1 %}
                    <a href="{{user.pending.url}}" title="{{user.pending.dates}}">1 Akceptuj</a>
                {% else %}
                    0
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <div class="form-actions">

        <button type="submit">Pobierz raport</button>

    </div>
</form>
</div>
<script>
    document.querySelector('#id_year').value = {{year}};

    function submit() {
        var id = this.getAttribute('id'),
            inputName = document.querySelector('input[name="'+id+'"]'),
            newBonus = inputName.value,
            xhttp = new XMLHttpRequest(),
            userid = id.substr(1),
            url = 'http://127.0.0.1:8000/bonus/forceb/' + userid + '/' + newBonus + '/';

        xhttp.onreadystatechange = function () {
            if(this.readyState == 4 && this.status == 200) {
                console.log(this.responseText);
            }
        };
        xhttp.open('GET', url, true );
        xhttp.send();
    }

    var buttons = document.querySelectorAll('.change');
    buttons.forEach(function(item){
        item.addEventListener('click', submit);

    });
</script>
{% else %}
    <p>Welcome, {{ user.username}}.
        You can`t view this page</p>
    {% endif %}
{% else %}
    <p>Welcome, new user. Please log in.</p>
{% endif %}


{% endblock content%}

user_view/templates/user_view/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> wakacje wakacje </title>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css'%}" >
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <script src="{% static 'script.js' %}"></script>

    {% block head %}

    {% endblock head %}
</head>
<body>
{% block menu %}
  <nav class="navbar navbar-dark bg-primary ">
  <div class="container">
      <a class="margin-none navbar-brand" href="{{ MAIN_URL }}user/">
          <img src ="{% static 'logo.png' %}" alt = "bonus wakacje manager" class="logo" />
      </a>
      <div class="align-middle">
        <div class="nav navbar-nav">
          <a class="nav-item nav-link" href="{{ MAIN_URL }}wniosek/">Złóż wniosek</a>
        {% if request.user.is_superuser %}
          <a class="nav-item nav-link" href="{{ MAIN_URL }}modkal/">Modyfikuj kalendarz</a>
          <a class="nav-item nav-link" href="{{ MAIN_URL }}admin/">Admin</a>
          <a class="nav-item nav-link" href="{{ MAIN_URL }}createuser/">Dodaj użytkownika</a>
        {% endif %}
          <a class="nav-item nav-link" href="{{ MAIN_URL }}sprawdz/">Sprawdź kalendarz</a>

        </div>

        <p class="align-right "><a class="nav-item nav-link" title="logout" href="{{ MAIN_URL }}logout/">Logout <span class="glyphicon glyphicon-star" aria-hidden="true"></span></a></p>
        <p class="align-right">{{ user.username }}</p>

      </div>
  </div>
</nav>
{% endblock menu %}

    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
</body>

</html>

user_view/templates/user_view/checkcallendar.html
{% extends 'user_view/base.html' %}

{% block head %}
<link rel="stylesheet" href="./../../static/admin.css">
{% endblock head %}
{% block content %}

<hr>
<form method="POST">
    {% csrf_token %}
    {{ form }}

    <div class="form-actions">

        <button type="submit">Sprawdź</button>

    </div>
</form>
{% if warunek is True %}
<link rel="stylesheet" href="./../../static/wniosek.css">
<div class="calendar-form just-see">
    <p data-d="{{td.day}}" data-m="{{td.month}}">{{ cal | safe }}</p>
</div>

<code data-used='{{daysused}}' data-ndu='{{ndu}}' data-d="{{user.bonus.bonus}}" style="display:none;"></code>
<script>
    var swieta = JSON.parse(document.querySelector('code').getAttribute('data-ndu'));
    var uzyte_dni = JSON.parse(document.querySelector('code').getAttribute('data-used'));
</script>
<script src="./../../static/kalendarz.js"></script>
{% endif %}
{% endblock content%}

user_view/templates/user_view/index.html
{% extends 'user_view/base.html' %}
{% block content %}

{% if user.is_authenticated %}
{% load static %}
    {% if user_is_manager %}
    <div class="row">
            <h3>Witaj, {{ user.first_name}}. Wartość Twojego bonusa to: <b>{{ user.bonus}}</b></h3>
            <a href="{{ MAIN_URL }}wniosek/"><button type="button" class="btn btn-success">Złóż wniosek</button></a>

    </div>
    <div class="row">
    <h3>Twój zespół:</h3>
    <table class="table table-striped" style="width:70%;">
            <tr><td>id</td><td>username</td><td>bonus</td><td>dni wzięte</td><td>manager</td><td>oczekujące</td></tr>
            {% for member in all_users %}
                {% if user.email == member.manager.email %}
                <tr>
                    <td>{{member.id}}</td>
                    <td>{{ member.username }}</td>
                    <td>{{ member.bonus.bonus}}</td>
                    <td class="bonusdays">{{ member.bonusdays.date_bonus}}</td>
                    <td>{{member.manager.email}}</td>
                    <td>
                        {% if member.pending.status == 1 %}
                            <a href="{{member.pending.url}}" title="{{member.pending.dates}}">1 Akceptuj</a>
                        {% else %}
                            0
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
            {% endfor %}
        </table>
  <p><img src ="{% static 'vac.jpg' %}" class="center" /></p>
    </div>
    {% else %}
    <div class="row">
        <h3>Witaj, {{ user.first_name}} {{ user.last_name}}. Wartość Twojego bonusa to: <b>{{ user.bonus}}</b></h3>
        <a href="../wniosek/"><button type="button" class="btn btn-success">Złóż wniosek</button></a>
    <p><img src ="{% static 'vac.jpg' %}" class="center" /></p>
    </div>
    {% endif %}
{% endif %}

{% endblock content%}

user_view/templates/user_view/modifycalendar.html
{% extends 'user_view/base.html' %}
{% block head %}
<link rel="stylesheet" href="./../../../../static/wniosek_admin.css">
{% endblock head %}
{% block content %}
{% if request.user.is_superuser %}
Złóż wprowadź korektę w kalendarzu <u>{{clinet_info.imie}} {{clinet_info.nazwisko}}</u>
<hr>
<p>Bonus pracownika {{clinet_info.imie}} {{clinet_info.nazwisko}}: <b> {{clinet_info.bonus}} </b> dni</p>
<p>Wzięte dni: <span class="bonusdays">{{ daysused }}</span></p>
<p id="ddw">
    <u></u>
    <span></span>
</p>
<div class="calendar-form">
    <p data-d="{{td.day}}" data-m="{{td.month}}">{{ cal | safe }}</p>
    <form method="POST">
        {% csrf_token %}
        {{ form }}

        <div class="form-actions">

            <button type="submit" class="submit">Złóż wniosek</button>

        </div>
    </form>
</div>
<code data-used='{{daysused}}' data-ndu='{{ndu}}' data-d="{{clinet_info.bonus}}" data-clientid="{{ clinet_info.id }}" data-clientfirstname="{{ clinet_info.imie }}" data-clientlastname="{{ clinet_info.nazwisko }}" style="display:none;"></code>

<script>
    var swieta = JSON.parse(document.querySelector('code').getAttribute('data-ndu'));
    var uzyte_dni = JSON.parse(document.querySelector('code').getAttribute('data-used'));
</script>
<script src="./../../../../static/calendar_admin.js"></script>

{% endif %}
{% endblock content%}

user_view/templates/user_view/pickuser.html
{% extends 'user_view/base.html' %}

{% block head %}
<link rel="stylesheet" href="./../../static/admin.css">
{% endblock head %}
{% block content %}

<hr>
<p>Wybierz urzytkownika, któremu chcesz zmodyfikować kalendarz</p>
<form method="POST">
    {% csrf_token %}
    {{ form }}

    <div class="form-actions">

        <button type="submit">Zmień</button>

    </div>
</form>
{% endblock content%}

user_view/templates/user_view/update-mail.html
<html>
<body>
<h3>Aktualizacja statusu Bonus Wakacje za miesiąc {{ month }} </h3>

<p>Potwierdź aktualizację statusu Bonus Wakacje.</p>
<p>Kliknięcie w link TAK podniesie wartość bonusa o 1.66 wszystkim użytkownikom.</p>
<p><a href="{{ url2 | escape }}">TAK</a> <a href="{{ url | escape }}">NIE</a>

</p>
<p></p>
</body>
</html>

user_view/templates/user_view/wniosek-mail.html
<html>
<body>
<h3>Wniosek o wykorzystanie bonusa</h3>

<p>Proszę o wypłacenie mi  BONUSA Wakacje o wartości {{ days }} dni. </p>
<p>Wartość BONUSA obejmuje dni:
<table>
    <tr>
{%for day in days_bonus%}
        <td>{{ day }}</td>
{%endfor%}
    </tr>
</table>

</p>
<p><a href="{{ url | escape }}">Kliknij w link aby zaakceptować.</a>

</p>

</body>
</html>

user_view/templates/user_view/wniosek.html
{% extends 'user_view/base.html' %}
{% block head %}
<link rel="stylesheet" href="./../../static/wniosek.css">
{% endblock head %}
{% block content %}

<p>Twój bonus to: <b> -- {{ user.bonus.bonus}} -- </b> dni</p>
<p>Wzięte dni: <span class="bonusdays">{{ user.bonusdays.date_bonus }}</span></p>
<p id="ddw">
    <u></u>
    <span></span>
</p>
<div class="calendar-form">
    <p data-d="{{td.day}}" data-m="{{td.month}}">{{ cal | safe }}</p>
    <form method="POST">
        {% csrf_token %}
        {{ form }}

        <div class="form-actions">

            <button type="submit" class="submit">Złóż wniosek</button>

        </div>
    </form>
</div>
<code data-used='{{used}}' data-ndu='{{ndu}}' data-d="{{user.bonus.bonus}}" style="display:none;"></code>
<script>
    var swieta = JSON.parse(document.querySelector('code').getAttribute('data-ndu'));
    var uzyte_dni = JSON.parse(document.querySelector('code').getAttribute('data-used'));
</script>
<script src="./../../static/calendar.js"></script>

{% endblock content%}